---
apiVersion: apps/v1
kind: Deployment
metadata: 
  name: fb-deploy
  labels:
    app: facebook
    env: lab

spec:
  replicas: 3
  selector:
    matchLabels:
      app: facebook
  template:
    metadata:
      labels:
        app: facebook
        env: lab
        version: AC_v1
    spec:
      containers:
        - name: fbcont1
          image: saikiranaervadocker/batch15d:15
          ports:
            - containerPort: 80
